"""================= FewShot Generalization vs Distribution Shift. ============================="""
"""############ CUB200-2011 ###########"""
########### Split-ID 1
split_id=1

####### 2 Shots.
### Multisimilarity
python fewshot_ood_main.py --finetune_criterion margin --finetune_shots 2 --finetune_lr_multi 10 --finetune_iter 1000 --finetune_only_last --checkpoint --data_hardness $split_id --kernels 6 --source $datapath --n_epochs 200 --log_online --project DML_OOD-Shift_FewShot_Study --group CUB_Shots-2_ID-1_Multisimilarity --seed 0 --gpu $gpu --bs 112 --samples_per_class 2 --loss multisimilarity --arch resnet50_frozen_normalize --embed_dim 512
python fewshot_ood_main.py --finetune_criterion margin --finetune_shots 2 --finetune_lr_multi 10 --finetune_iter 1000 --finetune_only_last --checkpoint --data_hardness $split_id --kernels 6 --source $datapath --n_epochs 200 --log_online --project DML_OOD-Shift_FewShot_Study --group CUB_Shots-2_ID-1_Multisimilarity --seed 1 --gpu $gpu --bs 112 --samples_per_class 2 --loss multisimilarity --arch resnet50_frozen_normalize --embed_dim 512

### ArcFace
python fewshot_ood_main.py --finetune_criterion margin --finetune_shots 2 --finetune_lr_multi 10 --finetune_iter 1000 --finetune_only_last --checkpoint --data_hardness $split_id --kernels 6 --source $datapath --n_epochs 200 --log_online --project DML_OOD-Shift_FewShot_Study --group CUB_Shots-2_ID-1_ArcFace --seed 0 --gpu $gpu --bs 112 --samples_per_class 2 --loss arcface --arch resnet50_frozen_normalize --embed_dim 512
python fewshot_ood_main.py --finetune_criterion margin --finetune_shots 2 --finetune_lr_multi 10 --finetune_iter 1000 --finetune_only_last --checkpoint --data_hardness $split_id --kernels 6 --source $datapath --n_epochs 200 --log_online --project DML_OOD-Shift_FewShot_Study --group CUB_Shots-2_ID-1_ArcFace --seed 1 --gpu $gpu --bs 112 --samples_per_class 2 --loss arcface --arch resnet50_frozen_normalize --embed_dim 512

### DiVA
python fewshot_diva_ood_main.py --finetune_criterion margin --finetune_shots 2 --finetune_lr_multi 10 --finetune_iter 1000 --finetune_only_last --checkpoint --data_hardness $split_id --kernels 6 --source $datapath --n_epochs 200 --log_online --project DML_OOD-Shift_FewShot_Study --group CUB_Shots-2_ID-1_DiVA --seed 0 --gpu $gpu --bs 108 --samples_per_class 2 --loss margin --batch_mining distance --diva_rho_decorrelation 1500 1500 1500 --diva_alpha_ssl 0.3 --diva_alpha_intra 0.3 --diva_alpha_shared 0.3 --arch resnet50_frozen_normalize --embed_dim 128
python fewshot_diva_ood_main.py --finetune_criterion margin --finetune_shots 2 --finetune_lr_multi 10 --finetune_iter 1000 --finetune_only_last --checkpoint --data_hardness $split_id --kernels 6 --source $datapath --n_epochs 200 --log_online --project DML_OOD-Shift_FewShot_Study --group CUB_Shots-2_ID-1_DiVA --seed 1 --gpu $gpu --bs 108 --samples_per_class 2 --loss margin --batch_mining distance --diva_rho_decorrelation 1500 1500 1500 --diva_alpha_ssl 0.3 --diva_alpha_intra 0.3 --diva_alpha_shared 0.3 --arch resnet50_frozen_normalize --embed_dim 128

### S2SD
python fewshot_ood_main.py --finetune_criterion margin --finetune_shots 2 --finetune_lr_multi 10 --finetune_iter 1000 --finetune_only_last --checkpoint --data_hardness $split_id --kernels 6 --source $datapath --n_epochs 200 --log_online --project DML_OOD-Shift_FewShot_Study --group CUB_Shots-2_ID-1_S2SD --seed 0 --gpu $gpu --bs 112 --samples_per_class 2 --loss s2sd --arch resnet50_frozen_normalize --embed_dim 512  --loss_s2sd_source margin --batch_mining rho_distance --miner_rho_distance_cp 0.4 --loss_margin_beta 0.6 --loss_s2sd_target margin --loss_s2sd_T 1 --loss_s2sd_w 50 --loss_s2sd_target_dims 1024 1536 2048 --loss_s2sd_feat_distill --loss_s2sd_feat_w 50 --loss_s2sd_pool_aggr --loss_s2sd_feat_distill_delay 0
python fewshot_ood_main.py --finetune_criterion margin --finetune_shots 2 --finetune_lr_multi 10 --finetune_iter 1000 --finetune_only_last --checkpoint --data_hardness $split_id --kernels 6 --source $datapath --n_epochs 200 --log_online --project DML_OOD-Shift_FewShot_Study --group CUB_Shots-2_ID-1_S2SD --seed 1 --gpu $gpu --bs 112 --samples_per_class 2 --loss s2sd --arch resnet50_frozen_normalize --embed_dim 512  --loss_s2sd_source margin --batch_mining rho_distance --miner_rho_distance_cp 0.4 --loss_margin_beta 0.6 --loss_s2sd_target margin --loss_s2sd_T 1 --loss_s2sd_w 50 --loss_s2sd_target_dims 1024 1536 2048 --loss_s2sd_feat_distill --loss_s2sd_feat_w 50 --loss_s2sd_pool_aggr --loss_s2sd_feat_distill_delay 0


####### 5 Shots.
### Multisimilarity
python fewshot_ood_main.py --finetune_criterion margin --finetune_shots 5 --finetune_lr_multi 10 --finetune_iter 1500 --finetune_only_last --checkpoint --data_hardness $split_id --kernels 6 --source $datapath --n_epochs 200 --log_online --project DML_OOD-Shift_FewShot_Study --group CUB_Shots-5_ID-1_Multisimilarity --seed 0 --gpu $gpu --bs 112 --samples_per_class 2 --loss multisimilarity --arch resnet50_frozen_normalize --embed_dim 512
python fewshot_ood_main.py --finetune_criterion margin --finetune_shots 5 --finetune_lr_multi 10 --finetune_iter 1500 --finetune_only_last --checkpoint --data_hardness $split_id --kernels 6 --source $datapath --n_epochs 200 --log_online --project DML_OOD-Shift_FewShot_Study --group CUB_Shots-5_ID-1_Multisimilarity --seed 1 --gpu $gpu --bs 112 --samples_per_class 2 --loss multisimilarity --arch resnet50_frozen_normalize --embed_dim 512

### ArcFace
python fewshot_ood_main.py --finetune_criterion margin --finetune_shots 5 --finetune_lr_multi 10 --finetune_iter 1500 --finetune_only_last --checkpoint --data_hardness $split_id --kernels 6 --source $datapath --n_epochs 200 --log_online --project DML_OOD-Shift_FewShot_Study --group CUB_Shots-5_ID-1_ArcFace --seed 0 --gpu $gpu --bs 112 --samples_per_class 2 --loss arcface --arch resnet50_frozen_normalize --embed_dim 512
python fewshot_ood_main.py --finetune_criterion margin --finetune_shots 5 --finetune_lr_multi 10 --finetune_iter 1500 --finetune_only_last --checkpoint --data_hardness $split_id --kernels 6 --source $datapath --n_epochs 200 --log_online --project DML_OOD-Shift_FewShot_Study --group CUB_Shots-5_ID-1_ArcFace --seed 1 --gpu $gpu --bs 112 --samples_per_class 2 --loss arcface --arch resnet50_frozen_normalize --embed_dim 512

### DiVA
python fewshot_diva_ood_main.py --finetune_criterion margin --finetune_shots 5 --finetune_lr_multi 10 --finetune_iter 1500 --finetune_only_last --checkpoint --data_hardness $split_id --kernels 6 --source $datapath --n_epochs 200 --log_online --project DML_OOD-Shift_FewShot_Study --group CUB_Shots-5_ID-1_DiVA --seed 0 --gpu $gpu --bs 108 --samples_per_class 2 --loss margin --batch_mining distance --diva_rho_decorrelation 1500 1500 1500 --diva_alpha_ssl 0.3 --diva_alpha_intra 0.3 --diva_alpha_shared 0.3 --arch resnet50_frozen_normalize --embed_dim 128
python fewshot_diva_ood_main.py --finetune_criterion margin --finetune_shots 5 --finetune_lr_multi 10 --finetune_iter 1500 --finetune_only_last --checkpoint --data_hardness $split_id --kernels 6 --source $datapath --n_epochs 200 --log_online --project DML_OOD-Shift_FewShot_Study --group CUB_Shots-5_ID-1_DiVA --seed 1 --gpu $gpu --bs 108 --samples_per_class 2 --loss margin --batch_mining distance --diva_rho_decorrelation 1500 1500 1500 --diva_alpha_ssl 0.3 --diva_alpha_intra 0.3 --diva_alpha_shared 0.3 --arch resnet50_frozen_normalize --embed_dim 128

### S2SD
python fewshot_ood_main.py --finetune_criterion margin --finetune_shots 5 --finetune_lr_multi 10 --finetune_iter 1500 --finetune_only_last --checkpoint --data_hardness $split_id --kernels 6 --source $datapath --n_epochs 200 --log_online --project DML_OOD-Shift_FewShot_Study --group CUB_Shots-5_ID-1_S2SD --seed 0 --gpu $gpu --bs 112 --samples_per_class 2 --loss s2sd --arch resnet50_frozen_normalize --embed_dim 512  --loss_s2sd_source margin --batch_mining rho_distance --miner_rho_distance_cp 0.4 --loss_margin_beta 0.6 --loss_s2sd_target margin --loss_s2sd_T 1 --loss_s2sd_w 50 --loss_s2sd_target_dims 1024 1536 2048 --loss_s2sd_feat_distill --loss_s2sd_feat_w 50 --loss_s2sd_pool_aggr --loss_s2sd_feat_distill_delay 0
python fewshot_ood_main.py --finetune_criterion margin --finetune_shots 5 --finetune_lr_multi 10 --finetune_iter 1500 --finetune_only_last --checkpoint --data_hardness $split_id --kernels 6 --source $datapath --n_epochs 200 --log_online --project DML_OOD-Shift_FewShot_Study --group CUB_Shots-5_ID-1_S2SD --seed 1 --gpu $gpu --bs 112 --samples_per_class 2 --loss s2sd --arch resnet50_frozen_normalize --embed_dim 512  --loss_s2sd_source margin --batch_mining rho_distance --miner_rho_distance_cp 0.4 --loss_margin_beta 0.6 --loss_s2sd_target margin --loss_s2sd_T 1 --loss_s2sd_w 50 --loss_s2sd_target_dims 1024 1536 2048 --loss_s2sd_feat_distill --loss_s2sd_feat_w 50 --loss_s2sd_pool_aggr --loss_s2sd_feat_distill_delay 0




"""############ CUB200-2011 ###########"""
########### Split-ID 1
split_id=1

###################### 2 Shots.
####### -20
### Multisimilarity
python fewshot_ood_main.py --dataset cars196 --finetune_criterion margin --finetune_shots 2 --finetune_lr_multi 10 --finetune_iter 1000 --finetune_only_last --checkpoint --data_hardness -20 --kernels 6 --source $datapath --n_epochs 200 --log_online --project DML_OOD-Shift_FewShot_Study --group CAR_Shots-2_ID-1_Multisimilarity --seed 0 --gpu $gpu --bs 112 --samples_per_class 2 --loss multisimilarity --arch resnet50_frozen_normalize --embed_dim 512
python fewshot_ood_main.py --dataset cars196 --finetune_criterion margin --finetune_shots 2 --finetune_lr_multi 10 --finetune_iter 1000 --finetune_only_last --checkpoint --data_hardness -20 --kernels 6 --source $datapath --n_epochs 200 --log_online --project DML_OOD-Shift_FewShot_Study --group CAR_Shots-2_ID-1_Multisimilarity --seed 1 --gpu $gpu --bs 112 --samples_per_class 2 --loss multisimilarity --arch resnet50_frozen_normalize --embed_dim 512

### ArcFace
python fewshot_ood_main.py --dataset cars196 --finetune_criterion margin --finetune_shots 2 --finetune_lr_multi 10 --finetune_iter 1000 --finetune_only_last --checkpoint --data_hardness -20 --kernels 6 --source $datapath --n_epochs 200 --log_online --project DML_OOD-Shift_FewShot_Study --group CAR_Shots-2_ID-1_ArcFace --seed 0 --gpu $gpu --bs 112 --samples_per_class 2 --loss arcface --arch resnet50_frozen_normalize --embed_dim 512
python fewshot_ood_main.py --dataset cars196 --finetune_criterion margin --finetune_shots 2 --finetune_lr_multi 10 --finetune_iter 1000 --finetune_only_last --checkpoint --data_hardness -20 --kernels 6 --source $datapath --n_epochs 200 --log_online --project DML_OOD-Shift_FewShot_Study --group CAR_Shots-2_ID-1_ArcFace --seed 1 --gpu $gpu --bs 112 --samples_per_class 2 --loss arcface --arch resnet50_frozen_normalize --embed_dim 512

### DiVA
python fewshot_diva_ood_main.py --dataset cars196 --finetune_criterion margin --finetune_shots 2 --finetune_lr_multi 10 --finetune_iter 1000 --finetune_only_last --checkpoint --data_hardness -20 --kernels 6 --source $datapath --n_epochs 200 --log_online --project DML_OOD-Shift_FewShot_Study --group CAR_Shots-2_ID-1_DiVA --seed 0 --gpu $gpu --bs 108 --samples_per_class 2 --loss margin --batch_mining distance --diva_rho_decorrelation 100 100 100 --diva_alpha_ssl 0.15 --diva_alpha_intra 0.15 --diva_alpha_shared 0.15 --arch resnet50_frozen_normalize --embed_dim 128
python fewshot_diva_ood_main.py --dataset cars196 --finetune_criterion margin --finetune_shots 2 --finetune_lr_multi 10 --finetune_iter 1000 --finetune_only_last --checkpoint --data_hardness -20 --kernels 6 --source $datapath --n_epochs 200 --log_online --project DML_OOD-Shift_FewShot_Study --group CAR_Shots-2_ID-1_DiVA --seed 1 --gpu $gpu --bs 108 --samples_per_class 2 --loss margin --batch_mining distance --diva_rho_decorrelation 100 100 100 --diva_alpha_ssl 0.15 --diva_alpha_intra 0.15 --diva_alpha_shared 0.15 --arch resnet50_frozen_normalize --embed_dim 128

### S2SD
python fewshot_ood_main.py --dataset cars196 --finetune_criterion margin --finetune_shots 2 --finetune_lr_multi 10 --finetune_iter 100 --finetune_only_last --checkpoint --data_hardness -20 --kernels 6 --source $datapath --n_epochs 200 --log_online --project DML_OOD-Shift_FewShot_Study --group CAR_Shots-2_ID-1_S2SD --seed 0 --gpu $gpu --bs 112 --samples_per_class 2 --loss s2sd --arch resnet50_frozen_normalize --embed_dim 512  --loss_s2sd_source margin --batch_mining rho_distance --miner_rho_distance_cp 0.3 --loss_margin_beta 0.6 --loss_s2sd_target margin --loss_s2sd_T 1 --loss_s2sd_w 50 --loss_s2sd_target_dims 1024 1536 2048 --loss_s2sd_feat_distill --loss_s2sd_feat_w 50 --loss_s2sd_pool_aggr --loss_s2sd_feat_distill_delay 0
python fewshot_ood_main.py --dataset cars196 --finetune_criterion margin --finetune_shots 2 --finetune_lr_multi 10 --finetune_iter 100 --finetune_only_last --checkpoint --data_hardness -20 --kernels 6 --source $datapath --n_epochs 200 --log_online --project DML_OOD-Shift_FewShot_Study --group CAR_Shots-2_ID-1_S2SD --seed 1 --gpu $gpu --bs 112 --samples_per_class 2 --loss s2sd --arch resnet50_frozen_normalize --embed_dim 512  --loss_s2sd_source margin --batch_mining rho_distance --miner_rho_distance_cp 0.3 --loss_margin_beta 0.6 --loss_s2sd_target margin --loss_s2sd_T 1 --loss_s2sd_w 50 --loss_s2sd_target_dims 1024 1536 2048 --loss_s2sd_feat_distill --loss_s2sd_feat_w 50 --loss_s2sd_pool_aggr --loss_s2sd_feat_distill_delay 0


###################### 5 Shots.
####### -20
### Multisimilarity
python fewshot_ood_main.py --dataset cars196 --finetune_criterion margin --finetune_shots 5 --finetune_lr_multi 10 --finetune_iter 1500 --finetune_only_last --checkpoint --data_hardness $split_id --kernels 6 --source $datapath --n_epochs 200 --log_online --project DML_OOD-Shift_FewShot_Study --group CAR_Shots-5_ID-1_Multisimilarity --seed 0 --gpu $gpu --bs 112 --samples_per_class 2 --loss multisimilarity --arch resnet50_frozen_normalize --embed_dim 512
python fewshot_ood_main.py --dataset cars196 --finetune_criterion margin --finetune_shots 5 --finetune_lr_multi 10 --finetune_iter 1500 --finetune_only_last --checkpoint --data_hardness $split_id --kernels 6 --source $datapath --n_epochs 200 --log_online --project DML_OOD-Shift_FewShot_Study --group CAR_Shots-5_ID-1_Multisimilarity --seed 1 --gpu $gpu --bs 112 --samples_per_class 2 --loss multisimilarity --arch resnet50_frozen_normalize --embed_dim 512

### ArcFace
python fewshot_ood_main.py --dataset cars196 --finetune_criterion margin --finetune_shots 5 --finetune_lr_multi 10 --finetune_iter 1500 --finetune_only_last --checkpoint --data_hardness $split_id --kernels 6 --source $datapath --n_epochs 200 --log_online --project DML_OOD-Shift_FewShot_Study --group CAR_Shots-5_ID-1_ArcFace --seed 0 --gpu $gpu --bs 112 --samples_per_class 2 --loss arcface --arch resnet50_frozen_normalize --embed_dim 512
python fewshot_ood_main.py --dataset cars196 --finetune_criterion margin --finetune_shots 5 --finetune_lr_multi 10 --finetune_iter 1500 --finetune_only_last --checkpoint --data_hardness $split_id --kernels 6 --source $datapath --n_epochs 200 --log_online --project DML_OOD-Shift_FewShot_Study --group CAR_Shots-5_ID-1_ArcFace --seed 1 --gpu $gpu --bs 112 --samples_per_class 2 --loss arcface --arch resnet50_frozen_normalize --embed_dim 512

### DiVA
python fewshot_diva_ood_main.py --dataset cars196 --finetune_criterion margin --finetune_shots 5 --finetune_lr_multi 10 --finetune_iter 1500 --finetune_only_last --checkpoint --data_hardness $split_id --kernels 6 --source $datapath --n_epochs 200 --log_online --project DML_OOD-Shift_FewShot_Study --group CAR_Shots-5_ID-1_DiVA --seed 0 --gpu $gpu --bs 108 --samples_per_class 2 --loss margin --batch_mining distance --diva_rho_decorrelation 100 100 100 --diva_alpha_ssl 0.15 --diva_alpha_intra 0.15 --diva_alpha_shared 0.15 --arch resnet50_frozen_normalize --embed_dim 128
python fewshot_diva_ood_main.py --dataset cars196 --finetune_criterion margin --finetune_shots 5 --finetune_lr_multi 10 --finetune_iter 1500 --finetune_only_last --checkpoint --data_hardness $split_id --kernels 6 --source $datapath --n_epochs 200 --log_online --project DML_OOD-Shift_FewShot_Study --group CAR_Shots-5_ID-1_DiVA --seed 1 --gpu $gpu --bs 108 --samples_per_class 2 --loss margin --batch_mining distance --diva_rho_decorrelation 100 100 100 --diva_alpha_ssl 0.15 --diva_alpha_intra 0.15 --diva_alpha_shared 0.15 --arch resnet50_frozen_normalize --embed_dim 128

### S2SD
python fewshot_ood_main.py --dataset cars196 --finetune_criterion margin --finetune_shots 5 --finetune_lr_multi 10 --finetune_iter 1500 --finetune_only_last --checkpoint --data_hardness $split_id --kernels 6 --source $datapath --n_epochs 200 --log_online --project DML_OOD-Shift_FewShot_Study --group CAR_Shots-5_ID-1_S2SD --seed 0 --gpu $gpu --bs 112 --samples_per_class 2 --loss s2sd --arch resnet50_frozen_normalize --embed_dim 512  --loss_s2sd_source margin --batch_mining rho_distance --miner_rho_distance_cp 0.3 --loss_margin_beta 0.6 --loss_s2sd_target margin --loss_s2sd_T 1 --loss_s2sd_w 50 --loss_s2sd_target_dims 1024 1536 2048 --loss_s2sd_feat_distill --loss_s2sd_feat_w 50 --loss_s2sd_pool_aggr --loss_s2sd_feat_distill_delay 0
python fewshot_ood_main.py --dataset cars196 --finetune_criterion margin --finetune_shots 5 --finetune_lr_multi 10 --finetune_iter 1500 --finetune_only_last --checkpoint --data_hardness $split_id --kernels 6 --source $datapath --n_epochs 200 --log_online --project DML_OOD-Shift_FewShot_Study --group CAR_Shots-5_ID-1_S2SD --seed 1 --gpu $gpu --bs 112 --samples_per_class 2 --loss s2sd --arch resnet50_frozen_normalize --embed_dim 512  --loss_s2sd_source margin --batch_mining rho_distance --miner_rho_distance_cp 0.3 --loss_margin_beta 0.6 --loss_s2sd_target margin --loss_s2sd_T 1 --loss_s2sd_w 50 --loss_s2sd_target_dims 1024 1536 2048 --loss_s2sd_feat_distill --loss_s2sd_feat_w 50 --loss_s2sd_pool_aggr --loss_s2sd_feat_distill_delay 0
